import type { ComponentDef, ComponentCategory } from './types';

export const COMPONENT_DEFS: ComponentDef[] = [
  // ─── BASIC ────────────────────────────────────────────────────────────────
  {
    id: 'battery',
    name: 'Battery',
    shortName: 'BAT',
    category: 'Basic',
    width: 80,
    height: 44,
    bodyColor: '#374151',
    headerColor: '#4B5563',
    icon: '🔋',
    pins: [
      { id: 'pos', label: '+', x: -44, y: 0, type: 'power' },
      { id: 'neg', label: '-', x: 44, y: 0, type: 'ground' },
    ],
    description: 'A battery is an electrochemical device that stores and provides electrical energy. It maintains a constant voltage difference between its positive (+) and negative (–) terminals.',
    howItWorks: 'Inside a battery, a chemical reaction moves electrons from the negative terminal through an external circuit to the positive terminal. This flow of electrons is electric current. A 9V battery provides 9 volts of potential difference.',
    applications: ['Portable electronics', 'Circuits requiring regulated DC power', 'Prototyping and testing'],
    tip: 'Always connect + to the positive rail and – to ground. Reversing polarity can damage components.',
    defaultProperties: { voltage: 9 },
  },
  {
    id: 'power_supply',
    name: 'Power Supply',
    shortName: 'VCC',
    category: 'Basic',
    width: 60,
    height: 40,
    bodyColor: '#1D4ED8',
    headerColor: '#2563EB',
    icon: '⚡',
    pins: [
      { id: 'vcc', label: 'VCC', x: 0, y: 24, type: 'power' },
    ],
    description: 'A power supply provides a stable voltage reference (VCC). In digital circuits, 5V VCC is standard for Arduino; 3.3V for many sensors and ESP modules.',
    howItWorks: 'VCC is the supply voltage rail. Components connected to VCC receive the full supply voltage, while ground (GND) is the reference at 0V.',
    applications: ['Digital logic circuits', 'Microcontroller power rails', 'Sensor power'],
    tip: 'Use a separate power supply symbol to keep your schematic clean when multiple ICs share the same supply.',
    defaultProperties: { voltage: 5 },
  },
  {
    id: 'ground',
    name: 'Ground',
    shortName: 'GND',
    category: 'Basic',
    width: 50,
    height: 40,
    bodyColor: '#374151',
    headerColor: '#4B5563',
    icon: '⏚',
    pins: [
      { id: 'gnd', label: 'GND', x: 0, y: -24, type: 'ground' },
    ],
    description: 'Ground (GND) is the 0V reference point for all voltage measurements in a circuit. Everything is measured relative to ground.',
    howItWorks: 'Ground acts as the return path for current. All grounds in a circuit should be connected together to establish a common reference.',
    applications: ['Voltage reference in all circuits', 'Return path for current', 'Noise reduction (shield ground)'],
    tip: 'All GND symbols in a schematic are connected together even if not shown with a wire.',
    defaultProperties: {},
  },
  {
    id: 'resistor',
    name: 'Resistor',
    shortName: 'R',
    category: 'Basic',
    width: 70,
    height: 30,
    bodyColor: '#78350F',
    headerColor: '#92400E',
    icon: '⬛',
    pins: [
      { id: 'a', label: 'A', x: -39, y: 0, type: 'bidirectional' },
      { id: 'b', label: 'B', x: 39, y: 0, type: 'bidirectional' },
    ],
    description: 'A resistor is a passive component that limits the flow of electric current. It obeys Ohm\'s Law: V = I × R.',
    howItWorks: 'Resistance is measured in Ohms (Ω). When current flows through a resistor, it drops voltage proportional to the resistance. A 220Ω resistor with 5V applied allows ~22.7mA of current.',
    applications: ['Limiting current to LEDs', 'Pull-up/pull-down for logic pins', 'Voltage dividers', 'Signal conditioning'],
    tip: 'For a standard LED, use a 220Ω–470Ω resistor with a 5V supply. Formula: R = (Vsupply - Vled) / Iled',
    defaultProperties: { resistance: 220 },
  },
  {
    id: 'led',
    name: 'LED',
    shortName: 'LED',
    category: 'Basic',
    width: 50,
    height: 44,
    bodyColor: '#F59E0B',
    headerColor: '#D97706',
    icon: '💡',
    pins: [
      { id: 'anode', label: 'A+', x: -29, y: 0, type: 'input' },
      { id: 'cathode', label: 'K-', x: 29, y: 0, type: 'output' },
    ],
    description: 'A Light Emitting Diode (LED) emits light when current flows through it in the forward direction. It is a type of diode that only conducts in one direction.',
    howItWorks: 'When forward biased (+ on anode, – on cathode), electrons and holes recombine in the semiconductor junction, releasing energy as photons. The color depends on the gap energy of the material used.',
    applications: ['Status indicators', 'Display backlighting', 'Communication signals', 'Lighting'],
    tip: 'Always use a current-limiting resistor in series with an LED. Without it, too much current flows and the LED burns out instantly.',
    defaultProperties: { color: 'red', forwardVoltage: 1.8 },
  },
  {
    id: 'push_button',
    name: 'Push Button',
    shortName: 'BTN',
    category: 'Basic',
    width: 50,
    height: 50,
    bodyColor: '#065F46',
    headerColor: '#047857',
    icon: '🔘',
    pins: [
      { id: 'p1', label: '1', x: -29, y: 0, type: 'bidirectional' },
      { id: 'p2', label: '2', x: 29, y: 0, type: 'bidirectional' },
    ],
    description: 'A momentary push button creates a temporary electrical connection when pressed and releases when you let go. It is the most common input device in electronics.',
    howItWorks: 'Inside the button, pressing it bridges a gap between two contacts. When released, a spring pushes the contacts apart. Current only flows while the button is held down.',
    applications: ['User input', 'Reset switches', 'Trigger signals', 'Keypad matrices'],
    tip: 'Use a pull-down resistor (10kΩ to GND) on the signal pin so the Arduino reads a clean LOW when the button is not pressed.',
    defaultProperties: { pressed: false },
  },
  {
    id: 'switch',
    name: 'Switch',
    shortName: 'SW',
    category: 'Basic',
    width: 60,
    height: 40,
    bodyColor: '#064E3B',
    headerColor: '#065F46',
    icon: '🔛',
    pins: [
      { id: 'com', label: 'COM', x: -34, y: 0, type: 'bidirectional' },
      { id: 'no', label: 'NO', x: 34, y: 0, type: 'bidirectional' },
    ],
    description: 'A toggle switch latches in an open or closed state. Unlike a push button, it stays in position when released.',
    howItWorks: 'When switched ON, a conductive bridge closes the circuit. When switched OFF, the bridge opens and current cannot flow.',
    applications: ['Power on/off controls', 'Mode selection', 'Enable/disable circuits'],
    tip: 'SPDT (Single Pole Double Throw) switches have 3 pins: COM and two positions. SPST (Single Pole Single Throw) is simpler with just on/off.',
    defaultProperties: { closed: false },
  },
  {
    id: 'potentiometer',
    name: 'Potentiometer',
    shortName: 'POT',
    category: 'Basic',
    width: 70,
    height: 60,
    bodyColor: '#4338CA',
    headerColor: '#4F46E5',
    icon: '🎚️',
    pins: [
      { id: 'vcc', label: 'VCC', x: -39, y: 0, type: 'power' },
      { id: 'wiper', label: 'SIG', x: 0, y: -34, type: 'output' },
      { id: 'gnd', label: 'GND', x: 39, y: 0, type: 'ground' },
    ],
    description: 'A potentiometer is a variable resistor with three terminals. Turning the knob changes the resistance between the wiper (middle) terminal and each end.',
    howItWorks: 'A resistive track connects the two end terminals. The wiper slides along it dividing the total resistance. The wiper output voltage is proportional to knob position: Vout = Vin × (position/max_position).',
    applications: ['Volume controls', 'Analog user input', 'Sensor calibration offsets', 'Brightness adjustment'],
    tip: 'Connect the outer pins to VCC and GND. Read the middle wiper pin with analogRead() on an Arduino. It returns 0–1023.',
    defaultProperties: { resistance: 10000, value: 0.5 },
  },

  // ─── SEMICONDUCTORS ────────────────────────────────────────────────────────
  {
    id: 'diode',
    name: 'Diode',
    shortName: '1N4007',
    category: 'Semiconductors',
    width: 60,
    height: 30,
    bodyColor: '#1E3A5F',
    headerColor: '#1D4ED8',
    icon: '▷',
    pins: [
      { id: 'anode', label: 'A', x: -34, y: 0, type: 'input' },
      { id: 'cathode', label: 'K', x: 34, y: 0, type: 'output' },
    ],
    description: 'A diode allows current to flow in only one direction — from anode (+) to cathode (–). It blocks current in the reverse direction.',
    howItWorks: 'At its core is a P-N junction. When the anode is positive relative to the cathode by more than ~0.7V (forward voltage), the junction conducts. Below this threshold or reversed, it blocks current.',
    applications: ['Reverse polarity protection', 'Rectifier circuits (AC to DC)', 'Voltage clamping', 'Flyback protection for motors'],
    tip: 'The silver band or stripe on the physical diode marks the cathode (–) terminal.',
    defaultProperties: {},
  },
  {
    id: 'npn_transistor',
    name: 'NPN Transistor',
    shortName: 'NPN',
    category: 'Semiconductors',
    width: 60,
    height: 70,
    bodyColor: '#1F2937',
    headerColor: '#374151',
    icon: 'Ⓣ',
    pins: [
      { id: 'base', label: 'B', x: -34, y: 0, type: 'base' },
      { id: 'collector', label: 'C', x: 34, y: -24, type: 'collector' },
      { id: 'emitter', label: 'E', x: 34, y: 24, type: 'emitter' },
    ],
    description: 'An NPN transistor is a three-terminal semiconductor device. A small current at the Base controls a larger current flow from Collector to Emitter.',
    howItWorks: 'When the base-emitter junction is forward biased (Vbe > 0.7V), the transistor turns ON and current flows from collector to emitter. Current gain (hFE or β) is typically 100–300, meaning 1mA base current controls 100–300mA collector current.',
    applications: ['Switching relays and motors', 'Logic level conversion', 'Signal amplification', 'LED drivers'],
    tip: 'For switching: connect base via a 1kΩ resistor to the control signal. Emitter goes to GND, collector connects to the load.',
  },
  {
    id: 'pnp_transistor',
    name: 'PNP Transistor',
    shortName: 'PNP',
    category: 'Semiconductors',
    width: 60,
    height: 70,
    bodyColor: '#1F2937',
    headerColor: '#374151',
    icon: 'Ⓟ',
    pins: [
      { id: 'base', label: 'B', x: -34, y: 0, type: 'base' },
      { id: 'collector', label: 'C', x: 34, y: 24, type: 'collector' },
      { id: 'emitter', label: 'E', x: 34, y: -24, type: 'emitter' },
    ],
    description: 'A PNP transistor is the complement of NPN. Current flows from Emitter to Collector when the Base is pulled LOW relative to the Emitter.',
    howItWorks: 'The PNP turns ON when Vbe < –0.7V (base is 0.7V lower than emitter). Emitter connects to VCC; pulling the base low allows current through the load connected to the collector.',
    applications: ['High-side switching', 'Current sources', 'Complementary push-pull outputs'],
    tip: 'PNP transistors are controlled by pulling the base LOW (towards GND). Often used when you need to switch to VCC instead of to GND.',
  },
  {
    id: 'nmos_transistor',
    name: 'N-Channel MOSFET',
    shortName: 'NMOS',
    category: 'Semiconductors',
    width: 60,
    height: 70,
    bodyColor: '#3B0764',
    headerColor: '#4C1D95',
    icon: 'Ⓜ',
    pins: [
      { id: 'gate', label: 'G', x: -34, y: 0, type: 'gate' },
      { id: 'drain', label: 'D', x: 34, y: -24, type: 'drain' },
      { id: 'source', label: 'S', x: 34, y: 24, type: 'source' },
    ],
    description: 'An N-channel MOSFET is a voltage-controlled switch. When Vgs exceeds the threshold voltage (~2–4V), the channel between Drain and Source opens and conducts.',
    howItWorks: 'Unlike a BJT, the MOSFET is voltage-controlled and requires almost no gate current. Applying voltage to the gate creates an electric field that forms a conductive channel between drain and source.',
    applications: ['High power switching (LEDs, motors)', 'H-bridge motor drivers', 'Power regulation', 'Logic level conversion'],
    tip: 'For Arduino control: connect Gate to a digital pin through 100Ω–1kΩ. Source to GND. Drain to the negative side of your load.',
  },

  // ─── ICs ──────────────────────────────────────────────────────────────────
  {
    id: 'ic_555',
    name: '555 Timer IC',
    shortName: '555',
    category: 'ICs',
    width: 90,
    height: 90,
    bodyColor: '#1C1C2E',
    headerColor: '#2D2D44',
    icon: '⏱',
    pins: [
      { id: 'gnd',     label: '1-GND',   x: -54, y: -30, type: 'ground' },
      { id: 'trig',    label: '2-TRIG',  x: -54, y: -10, type: 'input' },
      { id: 'out',     label: '3-OUT',   x: -54, y: 10,  type: 'output' },
      { id: 'reset',   label: '4-RST',   x: -54, y: 30,  type: 'input' },
      { id: 'ctrl',    label: '5-CV',    x: 54,  y: 30,  type: 'input' },
      { id: 'thresh',  label: '6-THR',   x: 54,  y: 10,  type: 'input' },
      { id: 'disch',   label: '7-DIS',   x: 54,  y: -10, type: 'output' },
      { id: 'vcc',     label: '8-VCC',   x: 54,  y: -30, type: 'power' },
    ],
    description: 'The 555 Timer is one of the most iconic integrated circuits ever made. It can generate precise time delays and oscillations using just a few resistors and capacitors.',
    howItWorks: 'In astable mode: the output oscillates between HIGH and LOW continuously, acting as a clock. In monostable mode: a single trigger pulse; produces one output pulse of fixed duration. The timing is set by: T = 1.1 × R × C',
    applications: ['LED blinkers', 'Tone generators / buzzers', 'Servo signal generation', 'PWM generation', 'Heartbeat circuits'],
    tip: 'Most beginner projects use astable mode. Connect pins 2 and 6 together, use Ra and Rb resistors plus capacitor C1. Pin 4 (RESET) must be tied HIGH to VCC for normal operation.',
  },
  {
    id: 'and_gate',
    name: 'AND Gate',
    shortName: 'AND',
    category: 'ICs',
    width: 70,
    height: 50,
    bodyColor: '#134E4A',
    headerColor: '#0F766E',
    icon: '&',
    pins: [
      { id: 'a', label: 'A', x: -44, y: -12, type: 'input' },
      { id: 'b', label: 'B', x: -44, y: 12,  type: 'input' },
      { id: 'y', label: 'Y', x: 44,  y: 0,   type: 'output' },
    ],
    description: 'An AND gate outputs HIGH only when ALL inputs are HIGH. It is the most fundamental building block of digital logic.',
    howItWorks: 'Truth table: A=0,B=0→Y=0 | A=0,B=1→Y=0 | A=1,B=0→Y=0 | A=1,B=1→Y=1. In CMOS logic, the output is the logical AND of all inputs.',
    applications: ['Enable circuits', 'Comparators', 'Address decoding', 'ALU building blocks'],
    tip: 'You can cascade AND gates: (A AND B) AND C gives a 3-input AND function.',
  },
  {
    id: 'or_gate',
    name: 'OR Gate',
    shortName: 'OR',
    category: 'ICs',
    width: 70,
    height: 50,
    bodyColor: '#134E4A',
    headerColor: '#0F766E',
    icon: '≥1',
    pins: [
      { id: 'a', label: 'A', x: -44, y: -12, type: 'input' },
      { id: 'b', label: 'B', x: -44, y: 12,  type: 'input' },
      { id: 'y', label: 'Y', x: 44,  y: 0,   type: 'output' },
    ],
    description: 'An OR gate outputs HIGH when ANY input is HIGH. The output is LOW only when all inputs are LOW.',
    howItWorks: 'Truth table: A=0,B=0→Y=0 | A=0,B=1→Y=1 | A=1,B=0→Y=1 | A=1,B=1→Y=1.',
    applications: ['Alarm circuits (any sensor triggers alarm)', 'Interrupt logic', 'Enable signals from multiple sources'],
    tip: 'OR gates are used when ANY of several conditions should trigger an output.',
  },
  {
    id: 'not_gate',
    name: 'NOT Gate (Inverter)',
    shortName: 'NOT',
    category: 'ICs',
    width: 60,
    height: 44,
    bodyColor: '#134E4A',
    headerColor: '#0F766E',
    icon: '¬',
    pins: [
      { id: 'a', label: 'A', x: -34, y: 0, type: 'input' },
      { id: 'y', label: 'Y', x: 34,  y: 0, type: 'output' },
    ],
    description: 'A NOT gate (inverter) outputs the opposite of its input. HIGH becomes LOW, LOW becomes HIGH.',
    howItWorks: 'Truth table: A=0→Y=1 | A=1→Y=0. The NOT gate is the simplest logic gate and is used everywhere in digital circuits.',
    applications: ['Signal inversion', 'Level conversion', 'Clock edge generation', 'Complementary output pairs'],
    tip: 'Two NOT gates in series equal a buffer (no inversion). Useful for signal restoration.',
  },
  {
    id: 'l298n',
    name: 'L298N Motor Driver',
    shortName: 'L298N',
    category: 'ICs',
    width: 100,
    height: 90,
    bodyColor: '#1C1917',
    headerColor: '#292524',
    icon: '⚙',
    pins: [
      { id: 'in1',   label: 'IN1',   x: -54, y: -30, type: 'input' },
      { id: 'in2',   label: 'IN2',   x: -54, y: -10, type: 'input' },
      { id: 'in3',   label: 'IN3',   x: -54, y: 10,  type: 'input' },
      { id: 'in4',   label: 'IN4',   x: -54, y: 30,  type: 'input' },
      { id: 'ena',   label: 'ENA',   x: 0,   y: -54, type: 'input' },
      { id: 'enb',   label: 'ENB',   x: 30,  y: -54, type: 'input' },
      { id: 'out1',  label: 'OUT1',  x: 54,  y: -30, type: 'output' },
      { id: 'out2',  label: 'OUT2',  x: 54,  y: -10, type: 'output' },
      { id: 'out3',  label: 'OUT3',  x: 54,  y: 10,  type: 'output' },
      { id: 'out4',  label: 'OUT4',  x: 54,  y: 30,  type: 'output' },
      { id: 'vcc',   label: 'VCC',   x: -20, y: -54, type: 'power' },
      { id: 'gnd',   label: 'GND',   x: -20, y: 54,  type: 'ground' },
    ],
    description: 'The L298N is a dual H-bridge motor driver IC that can control two DC motors independently in both directions at up to 2A per channel.',
    howItWorks: 'An H-bridge uses 4 transistors arranged in an H pattern. By switching pairs diagonally, current direction through the motor reverses. IN1/IN2 control Motor A; IN3/IN4 control Motor B. ENA/ENB enable each channel (can be used with PWM for speed control).',
    applications: ['Robot motor control', 'Stepper motor driving', 'Linear actuator control'],
    tip: 'For forward: IN1=HIGH, IN2=LOW. For reverse: IN1=LOW, IN2=HIGH. For PWM speed: send PWM to ENA pin.',
  },

  // ─── MICROCONTROLLERS ────────────────────────────────────────────────────
  {
    id: 'arduino_uno',
    name: 'Arduino Uno',
    shortName: 'UNO',
    category: 'Microcontrollers',
    width: 120,
    height: 100,
    bodyColor: '#004B7F',
    headerColor: '#0369A1',
    icon: '🤖',
    pins: [
      { id: 'd2',  label: 'D2',  x: -70, y: -36, type: 'bidirectional' },
      { id: 'd3',  label: 'D3',  x: -70, y: -24, type: 'bidirectional' },
      { id: 'd4',  label: 'D4',  x: -70, y: -12, type: 'bidirectional' },
      { id: 'd5',  label: 'D5',  x: -70, y: 0,   type: 'bidirectional' },
      { id: 'd6',  label: 'D6',  x: -70, y: 12,  type: 'bidirectional' },
      { id: 'd7',  label: 'D7',  x: -70, y: 24,  type: 'bidirectional' },
      { id: 'd8',  label: 'D8',  x: -70, y: 36,  type: 'bidirectional' },
      { id: 'd9',  label: 'D9',  x: -70, y: 48,  type: 'bidirectional' },
      { id: 'd10', label: 'D10', x: 70,  y: -36, type: 'bidirectional' },
      { id: 'd11', label: 'D11', x: 70,  y: -24, type: 'bidirectional' },
      { id: 'd12', label: 'D12', x: 70,  y: -12, type: 'bidirectional' },
      { id: 'd13', label: 'D13', x: 70,  y: 0,   type: 'bidirectional' },
      { id: 'a0',  label: 'A0',  x: 70,  y: 12,  type: 'analog' },
      { id: 'a1',  label: 'A1',  x: 70,  y: 24,  type: 'analog' },
      { id: 'a2',  label: 'A2',  x: 70,  y: 36,  type: 'analog' },
      { id: '5v',  label: '5V',  x: 0,   y: -60, type: 'power' },
      { id: 'gnd', label: 'GND', x: 30,  y: -60, type: 'ground' },
      { id: '3v3', label: '3V3', x: -30, y: -60, type: 'power' },
    ],
    description: 'The Arduino Uno is an open-source microcontroller board based on the ATmega328P. It has 14 digital I/O pins, 6 analog inputs, and can be programmed in C/C++ via the Arduino IDE.',
    howItWorks: 'The microcontroller executes code in a loop defined by setup() and loop(). Digital pins can be configured as INPUT or OUTPUT and set HIGH (5V) or LOW (0V). Analog pins convert voltage (0–5V) to a digital value (0–1023). PWM pins (~) simulate analog output.',
    applications: ['Robotics', 'Home automation', 'Sensor data collection', 'Motor control', 'LED projects', 'IoT prototyping'],
    tip: 'Pins marked with ~ (3, 5, 6, 9, 10, 11) support PWM. Use analogWrite(pin, 0-255) to control LED brightness or motor speed.',
  },

  // ─── OUTPUTS ──────────────────────────────────────────────────────────────
  {
    id: 'buzzer',
    name: 'Buzzer',
    shortName: 'BUZ',
    category: 'Outputs',
    width: 50,
    height: 50,
    bodyColor: '#1C1917',
    headerColor: '#292524',
    icon: '🔔',
    pins: [
      { id: 'pos', label: '+', x: -29, y: 0, type: 'input' },
      { id: 'neg', label: '-', x: 29,  y: 0, type: 'ground' },
    ],
    description: 'A buzzer converts electrical energy into sound. Active buzzers make sound whenever power is applied; passive buzzers need a frequency signal to generate different tones.',
    howItWorks: 'Piezoelectric buzzers use the piezo effect: applying voltage to a crystal causes it to vibrate. Active buzzers have a built-in oscillator and just need DC power. Passive buzzers are driven by a square wave from a microcontroller.',
    applications: ['Alarms and alerts', 'Feedback sounds', 'Tone generators', 'Game sounds'],
    tip: 'For a passive buzzer with Arduino: use tone(pin, frequency) to generate notes. tone(pin, 440) plays concert A.',
  },
  {
    id: 'dc_motor',
    name: 'DC Motor',
    shortName: 'MOTOR',
    category: 'Outputs',
    width: 60,
    height: 60,
    bodyColor: '#374151',
    headerColor: '#4B5563',
    icon: '⚙',
    pins: [
      { id: 'a', label: 'A', x: -39, y: 0, type: 'bidirectional' },
      { id: 'b', label: 'B', x: 39,  y: 0, type: 'bidirectional' },
    ],
    description: 'A DC motor converts electrical energy into rotational mechanical energy. The direction of rotation depends on current polarity; speed depends on voltage.',
    howItWorks: 'Current flowing through the motor\'s coil (armature) creates a magnetic field. This field interacts with the permanent magnet field, creating torque. Reversing current reverses rotation.',
    applications: ['Wheels and locomotion in robots', 'Fan and pump control', 'Conveyor belts', 'Drill mechanisms'],
    tip: 'Never connect a DC motor directly to an Arduino pin — it draws too much current. Use a transistor, L298N H-bridge, or relay.',
  },
  {
    id: 'servo_motor',
    name: 'Servo Motor',
    shortName: 'SERVO',
    category: 'Outputs',
    width: 80,
    height: 50,
    bodyColor: '#1C1917',
    headerColor: '#3F3F46',
    icon: '🎛',
    pins: [
      { id: 'sig', label: 'SIG', x: -49, y: 0,   type: 'signal' },
      { id: 'vcc', label: 'VCC', x: 0,   y: -29, type: 'power' },
      { id: 'gnd', label: 'GND', x: 49,  y: 0,   type: 'ground' },
    ],
    description: 'A servo motor is a precision actuator that rotates to a specific angle based on a PWM signal. Standard servos rotate from 0° to 180°.',
    howItWorks: 'A servo uses a PWM signal with 50Hz frequency. The pulse width determines position: 1ms = 0°, 1.5ms = 90°, 2ms = 180°. An internal feedback mechanism (potentiometer) ensures accurate positioning.',
    applications: ['Robot joints', 'RC car steering', 'Camera gimbals', 'Door locks', 'Robotic arms'],
    tip: 'Use the Arduino Servo library: servo.attach(pin); servo.write(angle); for easy control.',
  },

  // ─── SENSORS ──────────────────────────────────────────────────────────────
  {
    id: 'ldr',
    name: 'Light Sensor (LDR)',
    shortName: 'LDR',
    category: 'Sensors',
    width: 50,
    height: 44,
    bodyColor: '#713F12',
    headerColor: '#92400E',
    icon: '☀',
    pins: [
      { id: 'a', label: 'A', x: -29, y: 0, type: 'analog' },
      { id: 'b', label: 'B', x: 29,  y: 0, type: 'analog' },
    ],
    description: 'A Light Dependent Resistor (LDR) or photoresistor changes resistance based on light intensity. High light → low resistance. Darkness → high resistance.',
    howItWorks: 'The photosensitive material (cadmium sulfide) has electrons excited by photons. More electrons → higher conductivity → lower resistance. A voltage divider with a fixed resistor gives an analog voltage proportional to light.',
    applications: ['Automatic street lights', 'Smart blinds', 'Alarm systems', 'Camera light metering'],
    tip: 'Use a voltage divider: LDR in series with a 10kΩ resistor between VCC and GND. Connect the midpoint to analogRead(). Read the value 0–1023.',
  },
  {
    id: 'temp_sensor',
    name: 'Temperature Sensor (NTC)',
    shortName: 'TEMP',
    category: 'Sensors',
    width: 55,
    height: 44,
    bodyColor: '#7C2D12',
    headerColor: '#9A3412',
    icon: '🌡',
    pins: [
      { id: 'a', label: 'A', x: -29, y: 0, type: 'analog' },
      { id: 'b', label: 'B', x: 29,  y: 0, type: 'analog' },
    ],
    description: 'An NTC thermistor (Negative Temperature Coefficient) decreases in resistance as temperature increases. Used in a voltage divider, it provides an analog signal proportional to temperature.',
    howItWorks: 'At room temperature (25°C), a 10kΩ NTC has 10kΩ resistance. At 50°C it might be ~3.5kΩ. Using the Steinhart-Hart equation, you can calculate temperature from the measured resistance.',
    applications: ['Temperature monitoring', 'Thermostats', 'Overheating protection', 'Ambient temperature displays'],
    tip: 'Combine it with a 10kΩ resistor in a voltage divider. Use the analogRead value with the Steinhart-Hart equation or a lookup table to get Celsius.',
  },

  // ── Capacitor ──────────────────────────────────────────────────────────────
  {
    id: 'capacitor',
    name: 'Capacitor (Film/Ceramic)',
    shortName: 'CAP',
    category: 'Basic',
    width: 70,
    height: 36,
    bodyColor: '#374151',
    headerColor: '#4B5563',
    icon: '⊣⊢',
    pins: [
      { id: 'pos', label: '+', x: -35, y: 0, type: 'input' },
      { id: 'neg', label: '−', x: 35,  y: 0, type: 'output' },
    ],
    description: 'A capacitor stores electrical energy in an electric field between two conductive plates. It charges up when voltage is applied and releases energy when the voltage drops.',
    howItWorks: 'Charge Q = C × V, where C is capacitance in Farads and V is voltage. The charging time constant τ = R × C. After one τ, the cap charges to ≈63% of supply voltage.',
    applications: ['Power supply filtering', 'Timing circuits (with 555)', 'Signal coupling/decoupling', 'RC filters', 'Energy storage'],
    tip: 'Rule of thumb: ceramic caps (100nF) decouple high-frequency noise near IC power pins; electrolytic caps (100µF+) filter low-frequency ripple on power rails.',
    defaultProperties: { capacitance: '100nF' },
  },

  // ── Electrolytic Capacitor ──────────────────────────────────────────────────
  {
    id: 'electrolytic_cap',
    name: 'Electrolytic Capacitor',
    shortName: 'ELCAP',
    category: 'Basic',
    width: 70,
    height: 44,
    bodyColor: '#111827',
    headerColor: '#1F2937',
    icon: '+⊣',
    pins: [
      { id: 'pos', label: '+', x: -35, y: 0, type: 'input' },
      { id: 'neg', label: '−', x: 35,  y: 0, type: 'output' },
    ],
    description: 'Electrolytic capacitors are polarized — the positive leg must connect to the higher voltage. They offer high capacitance in small packages, making them ideal for power supply filtering.',
    howItWorks: 'The dielectric is a thin oxide film on the aluminum anode. The cathode is an electrolyte. If connected in reverse, the oxide is destroyed and the capacitor can fail. Mark the stripe on the can (−) or the shorter lead (−).',
    applications: ['Power supply filtering', 'Audio coupling', 'Motor start circuits', 'Bulk energy storage'],
    tip: 'Always observe polarity! The negative leg (-) has a white stripe printed on the can. The positive leg (+) is the longer lead.',
    defaultProperties: { capacitance: '10µF' },
  },

  // ── Inductor ───────────────────────────────────────────────────────────────
  {
    id: 'inductor',
    name: 'Inductor / Coil',
    shortName: 'IND',
    category: 'Basic',
    width: 80,
    height: 28,
    bodyColor: '#78350F',
    headerColor: '#92400E',
    icon: '∿∿∿',
    pins: [
      { id: 'a', label: 'A', x: -40, y: 0, type: 'input' },
      { id: 'b', label: 'B', x: 40,  y: 0, type: 'output' },
    ],
    description: 'An inductor (coil) stores energy in a magnetic field. It resists changes in current — when current tries to change, the inductor generates a back-EMF to oppose it.',
    howItWorks: 'Inductance L is measured in Henries (H). The voltage across an inductor is V = L × dI/dt. It passes DC freely but blocks AC — the opposite of a capacitor. Together they form LC circuits for filters and oscillators.',
    applications: ['EMI filters', 'DC-DC converters (buck/boost)', 'RF circuits', 'LC oscillators', 'Motor drives'],
    tip: 'An inductor in a relay coil creates a voltage spike when power is cut off (back-EMF). Always add a flyback diode across relay coils to protect your transistor/Arduino.',
    defaultProperties: { inductance: '10mH' },
  },

  // ── ESP32 ──────────────────────────────────────────────────────────────────
  {
    id: 'esp32',
    name: 'ESP32 Dev Board',
    shortName: 'ESP32',
    category: 'Microcontrollers',
    width: 100,
    height: 120,
    bodyColor: '#1E3A5F',
    headerColor: '#1D4ED8',
    icon: '📶',
    pins: [
      { id: '3v3',  label: '3.3V', x: -50, y: -50, type: 'power' },
      { id: 'gnd',  label: 'GND',  x: -50, y: -30, type: 'ground' },
      { id: 'en',   label: 'EN',   x: -50, y: -10, type: 'input' },
      { id: 'd0',   label: 'D0',   x: -50, y:  10, type: 'digital' },
      { id: 'd1',   label: 'D1',   x: -50, y:  30, type: 'digital' },
      { id: 'd2',   label: 'D2',   x: -50, y:  50, type: 'digital' },
      { id: 'vcc',  label: 'VIN',  x:  50, y: -50, type: 'power' },
      { id: 'gnd2', label: 'GND',  x:  50, y: -30, type: 'ground' },
      { id: 'd13',  label: 'D13',  x:  50, y: -10, type: 'digital' },
      { id: 'd12',  label: 'D12',  x:  50, y:  10, type: 'digital' },
      { id: 'd14',  label: 'D14',  x:  50, y:  30, type: 'digital' },
      { id: 'a0',   label: 'A0',   x:  50, y:  50, type: 'analog' },
    ],
    description: 'The ESP32 is a dual-core microcontroller with built-in WiFi (2.4GHz 802.11 b/g/n) and Bluetooth 4.2. It runs at up to 240MHz, has 520KB SRAM, and operates at 3.3V logic — NOT 5V tolerant!',
    howItWorks: 'The ESP32 runs FreeRTOS on two Xtensa LX6 cores. It supports Arduino programming, MicroPython, and ESP-IDF. It has 34 programmable GPIO, 18x 12-bit ADC channels, and 16 PWM channels.',
    applications: ['IoT devices', 'WiFi-controlled robots', 'Home automation', 'BLE beacons', 'Web servers on a chip'],
    tip: 'CRITICAL: ESP32 is 3.3V logic. Do NOT connect 5V signals to its GPIO — use a level shifter. Also, GPIO 6–11 are reserved for flash memory and must not be used.',
    defaultProperties: { running: false },
  },
];

export const COMPONENT_MAP: Record<string, ComponentDef> = Object.fromEntries(
  COMPONENT_DEFS.map(c => [c.id, c])
);

export const CATEGORIES: ComponentCategory[] = [
  'Basic',
  'Semiconductors',
  'ICs',
  'Microcontrollers',
  'Outputs',
  'Sensors',
];
